-- Ce fichier est intentionnellement vide.
-- L'initialisation des données est désormais gérée de manière programmatique via mg.ecomada.collect.common.config.DataInitializer.
-- Cette approche permet une meilleure gestion des relations et le hachage des mots de passe via BCrypt au démarrage.
